# HOW TO HANDLE A EXCEL FILE IN WHICH MULTIPLE EXCEL SHEETS ARE PRESENT

## FOR THAT IMPORT ALL RECOMMENDED PACKAGES

In [1]:
import pandas as pd

In [2]:
import numpy as np

### IF THAT EXCLE FILE IS IN XLSX FORMAT

#### CREATE OR LOAD A FILE WHICH CONTAINS MULTIPLE SHEETS IN ONE EXCEL FILE

##### IF YOU WANT TO LOAD XLSX FILE YOU TO INSTALL XLRD BY USING FOLLOWING SYNTAX
###### !pip install xlrd

## Following is the syntax for the code
### variable_name= pd.concat(pd.read_excel(r"file location.xlsx",sheet_name=None),

In [3]:
df = pd.concat(pd.read_excel(r"C:\Users\LENOVO\Desktop\sheets.xlsx",sheet_name=None),
              ignore_index=True)

In [4]:
df

,1,20,41,61,1597,1609,1627,1973,1992,1999,2005,2073,2130
0,1,NaN,NaN,62.0,1587.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,2051.0
1,1,NaN,NaN,63.0,1577.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1972.0
2,1,NaN,NaN,64.0,1567.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1893.0
3,1,NaN,NaN,65.0,1557.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1814.0
4,1,NaN,NaN,66.0,1547.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1735.0
5,1,NaN,NaN,67.0,1537.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1656.0
6,1,NaN,NaN,68.0,1527.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1577.0
7,1,NaN,NaN,69.0,1517.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1498.0
8,1,NaN,NaN,70.0,1507.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1419.0
9,1,NaN,NaN,71.0,1497.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1340.0
10,1,NaN,NaN,72.0,1487.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1261.0
11,1,NaN,NaN,73.0,1477.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1182.0
12,1,NaN,NaN,74.0,1467.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1103.0
13,1,NaN,NaN,75.0,1457.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,1024.0
14,1,NaN,NaN,76.0,1447.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,945.0
15,1,NaN,NaN,77.0,1437.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,866.0
16,1,NaN,NaN,78.0,1427.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,787.0
17,1,NaN,NaN,79.0,1417.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,708.0
18,1,NaN,NaN,80.0,1407.0,NaN,NaN,NaN,NaN,1999.0,NaN,NaN,629.0
19,1,21.0,NaN,NaN,NaN,NaN,1592.0,NaN,2063.0,NaN,NaN,2130.0,NaN
20,1,22.0,NaN,NaN,NaN,NaN,1634.0,NaN,1991.0,NaN,NaN,2088.0,NaN
21,1,23.0,NaN,NaN,NaN,NaN,1638.0,NaN,1916.0,NaN,NaN,2102.0,NaN
22,1,24.0,NaN,NaN,NaN,NaN,1593.0,NaN,1948.0,NaN,NaN,2123.0,NaN
23,1,25.0,NaN,NaN,NaN,NaN,1542.0,NaN,2034.0,NaN,NaN,2133.0,NaN
24,1,26.0,NaN,NaN,NaN,NaN,1601.0,NaN,2042.0,NaN,NaN,2015.0,NaN
25,1,27.0,NaN,NaN,NaN,NaN,1613.0,NaN,1936.0,NaN,NaN,1938.0,NaN
26,1,28.0,NaN,NaN,NaN,NaN,1644.0,NaN,2000.0,NaN,NaN,1974.0,NaN
27,1,29.0,NaN,NaN,NaN,NaN,1642.0,NaN,2046.0,NaN,NaN,1933.0,NaN
28,1,30.0,NaN,NaN,NaN,NaN,1605.0,NaN,2011.0,NaN,NaN,1925.0,NaN
29,1,31.0,NaN,NaN,NaN,NaN,1586.0,NaN,2066.0,NaN,NaN,1998.0,NaN
30,1,32.0,NaN,NaN,NaN,NaN,1577.0,NaN,2108.0,NaN,NaN,2032.0,NaN
31,1,33.0,NaN,NaN,NaN,NaN,1598.0,NaN,2066.0,NaN,NaN,1980.0,NaN
32,1,34.0,NaN,NaN,NaN,NaN,1561.0,NaN,2092.0,NaN,NaN,1942.0,NaN
33,1,35.0,NaN,NaN,NaN,NaN,1628.0,NaN,2142.0,NaN,NaN,1935.0,NaN
34,1,36.0,NaN,NaN,NaN,NaN,1694.0,NaN,2052.0,NaN,NaN,1965.0,NaN
35,1,37.0,NaN,NaN,NaN,NaN,1627.0,NaN,2081.0,NaN,NaN,1922.0,NaN
36,1,38.0,NaN,NaN,NaN,NaN,1598.0,NaN,2117.0,NaN,NaN,1950.0,NaN
37,1,39.0,NaN,NaN,NaN,NaN,1612.0,NaN,2075.0,NaN,NaN,1952.0,NaN
38,1,40.0,NaN,NaN,NaN,NaN,1630.0,NaN,2024.0,NaN,NaN,1958.0,NaN
39,1,NaN,42.0,NaN,NaN,1600.0,NaN,1983.0,NaN,NaN,2014.0,NaN,NaN
40,1,NaN,43.0,NaN,NaN,1608.0,NaN,1969.0,NaN,NaN,2024.0,NaN,NaN
41,1,NaN,44.0,NaN,NaN,1612.0,NaN,1957.0,NaN,NaN,2019.0,NaN,NaN
42,1,NaN,45.0,NaN,NaN,1605.0,NaN,1943.0,NaN,NaN,2018.0,NaN,NaN
43,1,NaN,46.0,NaN,NaN,1640.0,NaN,1917.0,NaN,NaN,2037.0,NaN,NaN
44,1,NaN,47.0,NaN,NaN,1610.0,NaN,1949.0,NaN,NaN,2077.0,NaN,NaN
45,1,NaN,48.0,NaN,NaN,1633.0,NaN,1930.0,NaN,NaN,2076.0,NaN,NaN
46,1,NaN,49.0,NaN,NaN,1573.0,NaN,1868.0,NaN,NaN,2058.0,NaN,NaN
47,1,NaN,50.0,NaN,NaN,1568.0,NaN,1944.0,NaN,NaN,1959.0,NaN,NaN
48,1,NaN,51.0,NaN,NaN,1576.0,NaN,2217.0,NaN,NaN,2059.0,NaN,NaN
49,1,NaN,52.0,NaN,NaN,1599.0,NaN,2045.0,NaN,NaN,2154.0,NaN,NaN
50,1,NaN,53.0,NaN,NaN,1620.0,NaN,1981.0,NaN,NaN,2168.0,NaN,NaN
51,1,NaN,54.0,NaN,NaN,1654.0,NaN,2069.0,NaN,NaN,2090.0,NaN,NaN
52,1,NaN,55.0,NaN,NaN,1637.0,NaN,2019.0,NaN,NaN,2160.0,NaN,NaN
53,1,NaN,56.0,NaN,NaN,1603.0,NaN,1992.0,NaN,NaN,2108.0,NaN,NaN
54,1,NaN,57.0,NaN,NaN,1605.0,NaN,2008.0,NaN,NaN,2075.0,NaN,NaN
55,1,NaN,58.0,NaN,NaN,1620.0,NaN,2001.0,NaN,NaN,2037.0,NaN,NaN
56,1,NaN,59.0,NaN,NaN,1616.0,NaN,2016.0,NaN,NaN,2052.0,NaN,NaN
57,1,NaN,60.0,NaN,NaN,1611.0,NaN,2019.0,NaN,NaN,2149.0,NaN,NaN

#### IF YOUR FILE IS IN CSV FORMAT IN THE CODE INSTEAD OF pd.read_excel GIVE pd.read_csv