# TO LOAD MULTIPLE CSV FILES IN ONE FILE FIRST IMPORT ALL NEEDED PACKAGES

In [5]:
import pandas as pd

In [11]:
import numpy as np

# THE DATA SET SHALL BE IN ZIP FILE FIRST EXTRACT IT 
### IN ONE FOLDER THERE WILL BE MULTIPLE FILES SELECT THE LOCATION OF THAT PARTICULAR FOLDER
#### THEN LOAD THAT FOLDER FOLDER 
##### THEN WRITE THE FOLLOWING CODE

In [10]:
path = r'C:\Users\LENOVO\DesktopActivity Recognition from Single Chest-Mounted Accelerometer' # use your path
all_files = glob.glob(path + "/*.csv")

li=[]

for filename in all_files:
   df = pd.read_csv(filename,index_col=None,header=0)
   li.append(df)
   
frame = pd.concat(li,axis=0,ignore_index=True,sort=False)
frame

NameError: name 'glob' is not defined

In [12]:
import glob #

In [14]:
path = r'C:\Users\LENOVO\Desktop\Activity Recognition from Single Chest-Mounted Accelerometer' # use your path
all_files = glob.glob(path + "/*.csv")

li=[]

for filename in all_files:
   df = pd.read_csv(filename,index_col=None,header=0)
   li.append(df)
   
frame = pd.concat(li,axis=0,ignore_index=True,sort=False)
frame

,61,1597,1999,2130,1,0,2082,2165,1702,1983,...,1629,1892,2279,1781,2057,2043,1665,2287,2948,2189
0,62.0,1587.0,1999.0,2051.0,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63.0,1577.0,1999.0,1972.0,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64.0,1567.0,1999.0,1893.0,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,65.0,1557.0,1999.0,1814.0,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,66.0,1547.0,1999.0,1735.0,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1764395,NaN,NaN,NaN,NaN,7,166740.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2072.0,2545.0,2059.0
1764396,NaN,NaN,NaN,NaN,7,166740.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2069.0,2547.0,2064.0
1764397,NaN,NaN,NaN,NaN,7,166740.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2069.0,2542.0,2062.0
1764398,NaN,NaN,NaN,NaN,7,166740.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2069.0,2543.0,2063.0
1764399,NaN,NaN,NaN,NaN,0,166740.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2065.0,2534.0,2060.0